# docker/Dockerfile.backend
FROM node:20-alpine

# Création du dossier de travail
WORKDIR /app

# Copier les fichiers du backend
COPY ./backend/package*.json ./
RUN npm install

COPY ./backend ./

# Exposition du port backend
EXPOSE 5010

# Lancement du serveur
CMD ["npm", "run", "dev"]
