# Utilise une image Python légère
FROM python:3.9-slim-buster

# Définis le répertoire de travail
WORKDIR /app

# Copie un script de test simple pour vérifier le fonctionnement
COPY test_python.py .

# Commande par défaut (peut être écrasée)
CMD ["python", "./test_python.py"]
